# Generated by Django 6.0.6 on 2026-06-27 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул/Штрихкод')),
                ('unit_type', models.CharField(choices=[('piece', 'Штучный'), ('weight', 'Весовой')], default='piece', max_length=10, verbose_name='Тип товара')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('ai_rating', models.FloatField(default=5.0, verbose_name='Текущий AI-рейтинг')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.RemoveField(
            model_name='writeoffrequest',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='writeoffrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='writeoffrequest',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Работник (Worker)'), ('manager', 'Менеджер (Manager)'), ('admin', 'Администратор (Admin)')], default='worker', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.branch', verbose_name='Филиал'),
        ),
        migrations.CreateModel(
            name='EmployeeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=255, verbose_name='Название бейджа')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Дата получения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Бейдж сотрудника',
                'verbose_name_plural': 'Бейджи сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата поставки')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Фотографии поставки')),
                ('ai_status_report', models.JSONField(blank=True, default=dict, verbose_name='AI Status Report')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='api.branch', verbose_name='Филиал')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='api.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='write_offs/', verbose_name='Фотография списания')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Вероятность распознавания AI')),
                ('reason', models.CharField(choices=[('expiration', 'Просрочка'), ('spoiled', 'Испорчен'), ('damaged', 'Поврежден'), ('cooking_error', 'Ошибка приготовления'), ('supplier_defect', 'Брак поставщика'), ('other', 'Другое')], max_length=20, verbose_name='Причина')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('status', models.CharField(choices=[('pending', 'На проверке (Pending)'), ('approved', 'Одобрено (Approved)'), ('rejected', 'Отклонено (Rejected)')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обработки')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='api.branch', verbose_name='Филиал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_write_offs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
        migrations.DeleteModel(
            name='WriteOffRequest',
        ),
    ]
