# Generated by Django 6.0.6 on 2026-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_product_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoff',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фотография списания (base64)'),
        ),
    ]
